export const ironmonMdx = `
# O Desafio IronMON
*Tradução por Tucabass*

IronMon é uma run de desafio de [Pokémon Randomizer](https://github.com/Ajarmar/universal-Pokemon-randomizer-zx/releases)
Challenge criada por [Iateyourpie](https://www.twitch.tv/iateyourpie) e projetada para fazer a experiência do randomizer divertida e desafiadora, enquanto tira o grind de pokemons selvagens que acompanha alguns dos outros desafios. Ela foi originalmente feita para Fire Red / Leaf Green mas as regras também podem ser aplicadas/ajustadas para outros jogos. Se você está interessado em mais informações a respeito de Ironmon, junte-se à [comunidade oficial](https://discord.gg/jFPYsZAhjX) ou à [comunidade brasileira de Randomizer](https://discord.gg/KTAYuY8M4b)!

IronMon tem níveis variáveis de dificuldade, para que seja mais acessível, mas também forneça o desafio mais árduo possível para aqueles que o quiserem.

### Regras para IronMon padrão

| Regra                      | Detalhes                                                                                                                                                                                      | Notas                                                                                                                  |
|---------------------------|----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|------------------------------------------------------------------------------------------------------------------------|
| Aleatorize o Jogo        | Todos os pokémons, movimentos, e itens são aleatorizados, com os níveis de pokémons de treinadores e pokémons selvagens aumentados em 50%.                                                                                 | Configuração completa do randomizer abaixo.                                                                                          |
| Capture ou mate 1 por Rota | Você pode capturar OU matar apenas um Pokémon por rota. <b>Não</b> precisa ser o primeiro que você vir. Além dessa exceção, toda a experiência (xp) deve ser adquirida em batalhas com treinadores.                                                    | Se você acidentalmente matar um Pokémon tentando capturá-lo, você não poderá capturar um Pokémon na rota em questão |
| Sem lojas                  | Você pode usar somente itens que você encontrar, não podendo comprar de lojas - exceto no caso de pokebolas e repelentes.                                                                                                    | Você não pode abusar o respawn de itens pegando-nos mais do que uma vez.                                                    |
| 1 time por vez          | Você pode carregar até 6 pokémons por vez e não pode retirar pokémons que foram depositados no PC.                                                                                        |                                                                                                                        |
| Morte permanente                | Se um Pokémon desmaiar, você deve libertar/guardar ele. Sem exceções.                                                                                                                             | Se um Pokémon morrer com um item equipado nele, o item não pode ser recuperado.                                            |
| Fim de jogo                 | Se todos os pokémons do seu time desmaiarem, a run acaba e você deve recomeçar com um novo jogo aleatorizado.                                                                                     |                                                                                                                        |
| Sem lendários            | Você não pode capturar Pokémons lendários. Treinadores os terão, mas você não pode pegar um Pokémon considerado “lendário”. Se um Pokémon evoluir e virar um lendário, você pode usá-lo. Mas apenas nessa situação. |                                                                                                                        |
| Itens Banidos              | Itens banidos: Lucky Egg, Sacred Ash.                                                                                                                                                         |                                                                                                                        |
| Sem lutar novamente              | Você não pode lutar novamente contra treinadores usando VS Seeker ou qualquer outro método em momento algum.                                                                                                               |                                                                                                                        |
| Pokémon inicial aleatório            | Você deve escolher o Pokémon inicial (starter) aleatoriamente antes de olhar as opções.                                                                                                                         |                                                                                                                        |
| Cláusula do favorito          | Você pode deixar de escolher o Pokémon inicial aleatoriamente APENAS se um dos seus 3 pokémons favoritos for uma opção.                                                                               | Por exemplo, Iateyourpie escolheu: Feraligatr, Wailord, e Tentacruel                                                    |
| Cláusula do brilhante              | Se você encontrar um Pokémon brilhante (shiny), você pode matá-lo pela experiência.                                                                                                                                | Você não pode aumentar a taxa de pokémons brilhantes usando o randomizer.                                                        |
| Não seja rude             | Você tem que falar com a mãe quando começar sua jornada, senão é rude.                                                                                                             |                                                                                                                        |

### Regras para Ultimate IronMon

Regras adicionais para gamers extremos (inclui todas as regras anteriores ao menos que seja explicitamente mencionado abaixo)

| Regra                    | Detalhes                                                                                                        | Notas                                                                                                                                                    |
|--------------------------|----------------------------------------------------------------------------------------------------------------|----------------------------------------------------------------------------------------------------------------------------------------------------------|
| Sem golpes de HM              | Sem golpes de HM nas batalhas.                                                                                          |                                                                                                                                                          |
| Ginásios sem saída          | A partir do momento que você entrar em um ginásio ou dojo, você deve derrotar TODOS OS TREINADORES + NÃO PODE SAIR ATÉ CONSEGUIR A INSÍGNIA. Vença ou morra.  |                                                                                                                                                          |
| Tentativa única em Calabouços        | Você pode entrar em calabouços apenas uma vez ao menos que a história exija que você volte nelas.                                           | Calabouço se refere a: - Qualquer esconderijo (hideout) - Qualquer caverna - Qualquer construção com treinadores                                                             | 6 Pokémon no total          | Você só pode adquirir 6 pokémons para a run inteira.                                                                | Se você perder 5 dos 6, você pode capturar outros para o uso de HM fora de batalhas apenas. Se esses pokémons forem colocados em batalha por alguma substituição forçada, você deve trocá-los imediatamente. |
| Taxas de crescimento flutuantes  | Todos os pokémons têm taxas de crescimento flutuantes, exceto os lendários, que são configurados como devagar.                          | Isso garante que nenhum Pokémon evolua e vire um lendário e um nível menor para o seu principal no final do jogo.                                                              |
| Itens banidos no Ultimate     | Itens banidos adicionais: Leftovers, Soul Dew.                                                                | Em adição aos itens banidos anteriormente.                                                                                                                   |
| Batalhas “Set” apenas       | Você deve usar batalhas tipo “Set” (e não “shift”) nas suas opções de jogo.                                                        |                                                                                                                                                          |
| Deixe seus amigos crescerem    | Se o seu Pokémon vai evoluir, você não pode interromper ou usar uma Everstone.                                        |                                                                                                                                                          |

Regras específicas para Ultimate IronMon FIRE RED/LEAF GREEN:
A) Você deve enfrentar imediatamente o rival no barco antes de outros treinadores no barco.
B) Você deve enfrentar o rival para sair de Lavender Town em sua primeira visita (volte depois para progressão).
C) Você não pode viajar para Sevii islands com o Bill antes de derrotar a Elite 4.

### Regras para Kaizo IronMon

Essas regras adicionais foram feitas para serem insanamente estúpidas e difíceis. Elas não foram feitas para serem justas e, possivelmente, nem mesmo divertidas. Mas, se você é realmente alguém que quer um desafio impossível, esse aqui é pra você. Essas regras não são negociáveis. Se você deseja ajustar as regras, só jogue IronMon Padrão ou Ultimate.

| Regra                               | Detalhes                                                                                                                                                                                                                                                                                                                                                                                                     | Notas                                                                                                                                                                                     |
|------------------------------------|-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| Um Pokémon por vez             | Você só pode usar um Pokémon, sempre. Os únicos Pokémons adicionais que você pode ter são amigos para HM. Se você quiser trocar por um Pokémon selvagem que você encontrar, você se compromete ao novo Pokémon no momento que o capturar AO MENOS QUE VOCÊ DIGA EXPLICITAMENTE QUE É UM AMIGO PARA HM ANTES (Amigos para HM não podem ser usados em substituições durante batalhas, aplicam-se as mesmas regras do ultimate. Você não precisa matar o seu amigo para HM se ele morrer). | Amigos para HM não podem ser usados para o seu benefício no caso de habilidades como Pick Up.                                                                                                       |
| Sem TMs aleatórios                       | Não é permitido usar TMs ou Move Tutor exceto pelas TMs que você receber de líderes de ginásio.                                                                                                                                                                                                                                                                                                                                       | Você deve usar os movimentos que o seu Pokémon aprender naturalmente ou TMs de líderes de ginásio.                                                                                                           |
| Sem Pokémons super fortes                | Nada de usar Pokémons com BST 599+ e nada de lendários                                                                                                                                                                                                                                                                                                                                                                  | Um pokémons lendário pode ser um dos seus 3 pokémons para a cláusula de favorito, mas ele deve ter menos que 600 BST.                                                                                          |
| Mantenha-se em sua categoria de peso          | Após conquistar sua primeira insígnia, você só pode capturar um Pokémon que tenha um nível menor ou igual ao do seu Pokémon atual.                                                                                                                                                                                                                                                                                    |                                                                                                                                                                                           |
| Sem movimentos de cura                   | Sem movimentos de cura de qualquer tipo (Recover, Milk Drink etc, sem Drainpunch etc, sem Leech Seed. Sem Refresh/Aroma etc) Sem Spore. Sem Assist. Não inclui Metronome.                                                                                                                                                                                                                                         | Se o seu Pokémon inicial tiver um movimento banido, você pode usá-lo apenas no confronto do laboratório. Movimentos de cura não podem ser usados sob circunstância alguma fora do laboratório, mesmo com vida cheia.  |
| Habilidades banidas                   | Huge Power/Pure Power. Se o seu Pokémon inicial tiver uma habilidade banida, você pode usá-la apenas no confronto do laboratório. Após sair do laboratório, você deve trocá-lo.                                                                                                                                                                                                                                                           | Se, em qualquer momento depois do laboratório, o seu Pokémon principal possuir uma dessas habilidades, você deve encontrar uma habilidade nova antes da próxima batalha de treinador.                                                   |
| Nada de matar pokémons selvagens            | A regra de capturar ou matar agora é capturar apenas. Não lute contra nenhum Pokémon selvagem.                                                                                                                                                                                                                                                                                                                                     | Se algo explodir, etc, tudo bem. Mas evite derrotar Pokémons selvagens a qualquer custo.                                                                                                    |
| Sem itens de cura fora de batalhas | Sem itens que curem HP enquanto estiver fora de uma batalha.                                                                                                                                                                                                                                                                                                                                                                 | Isso inclui curas de status e itens de recuperação de PP. PP UP/PP MAX podem ser usados for a de batalha.                                                                                               |
| Restrições para Held Items             | Os únicos Held Items permitidos são itens de evolução e itens consumíveis como berries EXCETO Focus Sash.                                                                                                                                                                                                                                                                  ||
| Sem estações de cura em calabouços    | Nada curas no estilo de pokecentros dentro de calabouços (Exemplo: Rocket Hideout NPC, cama no SS Anne, etc)                                                                                                                                                                                                                                                                                                                     | Curas forçadas pela história são permitidas, mas você não pode voltar pra usar mais.                                                                                                                       |
| Itens banidos no Kaizo                 | Nada de usar itens de flauta para curar efeitos de status.                                                                                                                                                                                                                                                                                                                                                                |                                                                                                                                                                                           |
| Configuração do Randomizer para Kaizo          | Algumas configurações específicas para Kaizo: - Pokémons estáticos NÃO PODEM ter aumento de nível - Sem "Make Evolutions Easier" (tornar evoluções mais fáceis) - Evolução completa forçada no nível 30 - Adicionar 3 pokémons adicionais a treinadores chefes                                                                                                                                                                                     | Algumas configurações podem não estar disponíveis para todas as gerações.                                                                                                                                 |
| Sem abuso de reaprender                | Você pode usar Move Relearner mas não pode reaprender o mesmo movimento várias vezes.                                                                                                                                                                                                                                                                                                                                   |                                                                                                                                                                                           |
| Mortes acidentais                   | Se você acidentalmente matar um Pokémon tentando encontrar uma possível troca, você NÃO PRECISA resetar a run, mas você deve trocar para um dos pokémons da rota em questão antes de sair.                                                                                                                                                                                                                                     | Isso significa que você não pode ir se curar ATÉ capturar um Pokémon novo para trocar.                                                                                                               |

## Perguntas Frequentes

> P: Onde eu posso encontrar o randomizer?\n
> R: https://github.com/Ajarmar/universal-Pokemon-randomizer-zx/releases

> P: Eu posso resetar imediatamente se eu não gostar do meu Pokémon inicial?\n
> R: E qual seria a graça? Tentar jogar é o espírito do desafio, você pode se surpreender com quão longe você pode ir.

> P: Quais são as configurações do randomizer?\n
> R: Link para as configurações básica do randomizer: [IronMon Settings PNG](https://cdn.discordapp.com/attachments/251538607578284033/809211676905177138/Updated_ironMON_Settings.png).

> P: Existe uma forma de configurar o randomizer facilmente?\n
> R: Junte-se à comunidade do IronMon no [servidor oficial](https://discord.gg/jFPYsZAhjX) ou na [RandoBrasil](https://discord.gg/KTAYuY8M4b) para uma sequência atualizada das configurações para carregar as configurações facilmente e tirar qualquer dúvida

> P: Quem eu posso ~~reclamar~~ agradecer por ter criado esse desafio?\n
> R: Links do Iateyourpie para [Twitch](https://www.twitch.tv/iateyourpie), [Twitter](https://twitter.com/Iateyourp1e), and [Youtube](https://www.youtube.com/channel/UCAwIbbB6OE1OAd-gisAl5jA).
`
